### PR TITLE
adapt qmake files and Qt header #includes where necessary, use Qt5 pl…

### PR DESCRIPTION
**Pull request by edogawa23**
…ugin handling method and replace obsolete QtFSFileEngine calls.

I've just done what was necessary to make the code compile; the changes regarding plugin loading follow what I found on the web. As I can't test if these changes still will compile against Qt4, I'm unsure if the Qt version check surrounding the deprecated macro makes sense at all. Also please review the code changes regarding QtFSFileEngine replacement I tried to use QFile/QDir calls instead.

### CODE REVIEW

**Comment by trebmuh** [comment]
ping @surfacepatterns

**Comment by surfacepatterns** [comment]
Hi!  I apologize for the delay.  Life is hectic.

I haven't maintained `synthclone` since September, 2013 or so.  I'm *really* happy that there's still interest in `synthclone`, but I don't have the time, the resources, or the motivation to maintain the application at this point in time.  Even if I did have those things, I don't currently have a machine with a pro-audio Linux build that I can use to test the PR.  The best I can do at this point is review the PR and tell you if it looks reasonable.

**Comment by edogawa23** [comment]
As I said my main motivation for this was to keep my package working in openSUSE, where like in many other distros Qt4 is being phased out since a while. I can assure that it compiles and runs, and the file chooser works, but i suspect that the changes to #include paths for Qt5 all should become conditional (if Qt4 compatibility should be kept at all).
This is a pretty unique app and it's a pity you cannot spend time on it or someone else takes over.
I'm sadly not available either, with a day job, kids and several other duties/interests, I'm able to maintain the package and spend a little time occasionally, but that's about it. I haven't even found time to actually start using it on my vintage synths... 

maybe a mail to LAU and/or LAD mailing lists could help?

**Comment by dromer** [comment]
Note: on debian `qmake-qt5` is just called `qmake`.

**Comment by surfacepatterns** [comment]
Thank you for your contribution.  I'm sorry I wasn't motivated enough to review and accept the contribution back when you made it.

In the past couple days, I put some effort into updating `synthclone` to work with Qt6, and it's now working in the `master` (I'll be renaming the branch `main` shortly) branch.

I'm going to go ahead and close this PR.

Thanks again. :)

**Pull request closed without merging**
